id: github_sys_sync_namespacefiles
namespace: system
description: |
  Source scripts (like python or bash files) developed outside of Kestra (in VS Code)
  from a Github repo to Kestra Namespace Files. 

  Namespace Files are used by multiple flows within a namespace in Kestra.

labels:
  - key: demo
    value: github_integration
  - key: maintainer
    value: parham
  - key: concepts 
    value: nsfiles, SyncNamespaceFiles, NamespaceSync

# ==== Flow Triggers ====
# How this flow is triggered to run:
#  1- via a webhook call from Github Actions (ie: commits to branch)
#  2- On a regular schedule
triggers:
  - id: on_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{secret('YOUR_WEBHOOK_TOKEN')}}"
    disabled: false
    
  - id: on_15min_interval
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"
    disabled: true

# ==== Flow Input Parameters =====
# These params can be used if this Flow is run manually.
# Useful to dynamically sync specific namesapces and branches.
# Set default values if the flow is run via other triggers above.
inputs:
  - id: branch
    type: STRING
    defaults: "kestra"
  - id: namespace
    type: STRING
    defaults: "solutions.github_integration"


tasks:
  # ==== SyncNamespaceFiles plugin ====
  # this plugin syncs scripts/files from git into namespace files
  # these scripts are then shared by multiple flows within that 
  # namespace
  - id: sync_namespace_files
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: "https://github.com/xdatanomad/kestra-demo.git"
    username: xdatanomad
    # this repo is public (no need to PAT)
    # to access private repos, you must use a github PAT
    # password: "{{ secret('github_token') }}"
    gitDirectory: "kestra/solutions/github_integration/files"
    branch: "{{ inputs.branch }}"
    namespace: "{{ inputs.namespace }}"
    dryRun: false

  # # ==== NamespaceSync Kestra EE plugin ====
  # # this plugin is only available in Kestra Enterprise Edition (EE)
  # # **warning**: this plugin will sync both kestra Flows and Namespace
  # # files. 
  # - id: sync_namespace
  #   type: io.kestra.plugin.git.NamespaceSync
  #   sourceOfTruth: KESTRA
  #   protectedNamespaces:
  #     - system
  #   url: "https://github.com/xdatanomad/kestra-demo.git"
  #   username: xdatanomad
  #   password: "{{ secret('github_token') }}"
  #   gitDirectory: "kestra/solutions/github_integration/"
  #   branch: "{{ inputs.branch }}"
  #   namespace: "{{ inputs.namespace }}"
  #   whenMissingInSource: KEEP
  #   dryRun: true