[windows_vms]
{{ kv('dcConfig').externalIPAddress }}

[windows_vms:vars]
ansible_user={{ kv('dcConfig').username }}
ansible_password="{{ secret('AD_CONTROLLER_PW') }}"
ansible_connection=winrm
ansible_port=5985
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm