apiVersion: 1

templates:
  - orgId: 1
    name: kestra_alert_message
    template: |
      {{ define "kestra_alert_message" }}
      {{ range .Alerts }}
      {{ .Annotations.summary }}
      {{ if eq .Status "firing" }}Current value: {{ printf "%.1f" (index .Values "A") }}{{ .Labels.unit }} (threshold: {{ .Labels.threshold }}{{ .Labels.unit }})

      Action: {{ .Annotations.description }}{{ end }}
      {{ end }}
      {{ end }}
  - orgId: 1
    name: kestra_alert_title
    template: |
      {{ define "kestra_alert_title" }}{{ if eq .Status "firing" }}FIRING{{ else }}RESOLVED{{ end }}: {{ .CommonLabels.alertname }}{{ if .CommonLabels.instance }} ({{ .CommonLabels.instance }}){{ end }}{{ end }}
